services:
  linkding:
    image: ${IMAGE:-sissbruecker/linkding}:${TAG:-latest}
    container_name: ${CONTAINER_NAME:-linkding}
    ports:
      - "${HOST_PORT:-9090}:${CONTAINER_PORT:-9090}"
    volumes:
      - ${DATA_VOLUME_NAME:-linkding-data}:/etc/linkding/data
    restart: unless-stopped

volumes:
  ${DATA_VOLUME_NAME:-linkding-data}:
