#!/usr/bin/env bash
# gen_skill_required_fields.sh
#
# Reads doc/openapi.json and regenerates the AUTO-GENERATED REQUIRED FIELDS
# section in skills/api-catalog/SKILL.md so it can never drift from the spec.
#
# Usage:  bash api/scripts/gen_skill_required_fields.sh
# Or add to Makefile:  make gen-skill
#
# The script replaces the block between the markers:
#   <!-- BEGIN REQUIRED FIELDS (auto-generated) -->
#   <!-- END REQUIRED FIELDS (auto-generated) -->
# If the markers are absent the block is appended.

set -euo pipefail

SPEC="api/doc/openapi.json"
SKILL="api/skills/api-catalog/SKILL.md"
BEGIN_MARKER="<!-- BEGIN REQUIRED FIELDS (auto-generated) -->"
END_MARKER="<!-- END REQUIRED FIELDS (auto-generated) -->"

if [[ ! -f "$SPEC" ]]; then
  echo "ERROR: $SPEC not found. Start the server once to generate it." >&2
  exit 1
fi

# Build the new block via jq
BLOCK=$(jq -r '
  .components.schemas
  | to_entries[]
  | select(.key | endswith("Request"))
  | . as $entry
  | .value.required // []
  | if length > 0 then
      "### \($entry.key) — required fields\n" +
      (
        $entry.value.properties
        | to_entries[]
        | select(.key as $k | $entry.value.required | index($k) != null)
        | "- `\(.key)` (\(.value.type // "object")): \(.value.description // "")"
      )
    else empty end
' "$SPEC" 2>/dev/null)

NEW_BLOCK="${BEGIN_MARKER}
## REQUIRED FIELDS (auto-generated from openapi.json — do not edit manually)
All fields below are marked \`validate:\"required\"\` in the Go source and WILL cause
HTTP 400 if omitted. This section is regenerated by \`make gen-skill\`.

${BLOCK}
${END_MARKER}"

if grep -q "$BEGIN_MARKER" "$SKILL"; then
  # Replace between markers
  perl -i -0pe "s|\Q${BEGIN_MARKER}\E.*?\Q${END_MARKER}\E|${NEW_BLOCK//\//\\/}|s" "$SKILL"
  echo "✓ Updated required fields block in $SKILL"
else
  # Append
  printf "\n%s\n" "$NEW_BLOCK" >> "$SKILL"
  echo "✓ Appended required fields block to $SKILL"
fi
