services:
  uptime-kuma:
    image: ${IMAGE:-louislam/uptime-kuma}:${TAG:-1}
    container_name: ${CONTAINER_NAME:-uptime-kuma}
    ports:
      - "${HOST_PORT:-3001}:3001"
    volumes:
      - uptime-kuma:/app/data
    restart: always

volumes:
  uptime-kuma:
